### ISSUE TITLE
EvaluateExAsync with variable

### ISSUE THREAD

**Issue by mossbeard** [q2g/enigma.net#14]
If I want to calculate a variable with the method "EvaluateEx" i come to an exception.
Do it this over the devhub I get the correct result.
If I do this over the json overload from "EvaluateEx", then i get correct result.
Line: 157

**Comment by konne** [comment]
@mossbeard new nuget https://www.nuget.org/packages/enigma.net/0.12.0 should be online.
Versioning will be fixed starting from 1.0
