### ISSUE TITLE
Handle Multiple parallel Requests

### ISSUE THREAD

**Issue by ChristofHoldschick** [q2g/enigma.net#15]
@konne , at the moment there are errors when calling CreateSessionObjectAsync and GetLayoutAsync multiple times parallel.

**Comment by ChristofHoldschick** [comment]
If GetLayoutAsync is not get called, no error is shown.

**Comment by konne** [comment]
@ChristofHoldschick just another strange finding from me.
The error only occurs if I start it with .NET452 in .netcore2.1 everything is running create.
I will find and fix the rootcause

**Comment by konne** [comment]
@ChristofHoldschick please test should be fixed in enigma.net.0.13.0.nupkg
