### ISSUE TITLE
Sender Object in Changehandler of IGenericObject

### ISSUE THREAD

**Issue by ChristofHoldschick** [q2g/enigma.net#18]
Problem:
the Senderobject in the changehandler of an IGenericObject is of Type GeneratedAPI and is somtimes castable to IGenericObject and somtimes not (for instance, when it is triggered by a selection).

the Function ChangeEventSample.CachedCurrentSelection_Changed is the Point Where the cast-problem occours.

**Comment by ChristofHoldschick** [comment]
the Cast is working now, but when GetLayoutAsync is called on them, the Request never returns.
Seems like GetlayoutAsync-calls in ChangeEvents, triggered by examamplecode, are working, but
GetlayoutAsync-calls in ChangeEvents, triggered by enigma, never returns.

Updated Example, commented out the line that triggers the ChangeHandler manually, so only Enigma changehandler-Calls are firing

**Comment by konne** [comment]
@ChristofHoldschick please check the new version. 
Important side info you have to call GetLayout to get a changed event.
