### ISSUE TITLE
Waiting for an response from Qlik

### ISSUE THREAD

**Issue by mossbeard** [q2g/enigma.net#21]
Es kommt hin und wieder vor das Enigma einen Request verschickt aber keinen Response von Qlik erhält.
Dann bleibt er einfach stehen, ich wollte hiermit auf dieses Problem aufmerksam machen. Leider haben weder Christof noch Ich für dieses Verhalten ein Beispiel bauen können, da es nur sporadisch auf tritt.

Ich habe diesen Zustand mal in einem Screenshot abgebildet.
Es wird ein Request verschickt, aber es kommt vermutlich keine Antwort von Qlik.
Es wäre gut wenn er nach einer bestimmten Zeit zumindestens abbbrechen könnte.
![grafik](https://user-images.githubusercontent.com/26477924/47064712-d4ed4880-d1e0-11e8-8a27-09b739c65cbe.png)

**Comment by mossbeard** [comment]
@konne Ich habe jetzt im "Development" Branch ein Beispiel in Zeile 53 Progam.cs hinzugefügt. Ich musste es deutlich komplexer gestallten, da sonst das Problem mit JToken null nicht auftritt.

**Comment by konne** [comment]
@mossbeard please test, I have fixed only the clear message for abort, so and testet an result =  {}
So I think your issue is still comming from you, because something is overlapping betwenn calculation and the call AbortModalAsync
